# See https://docs.docker.com/compose/compose-file/ for information about what
# commands you can use in this file.
#
# Note that you must use the `docker stack deploy` command, with any required
# command line flags, in order to actually get any replicas started. That
# command requires that a docker swarm is already running in order to function.

version: "3"
services:
  kademliaMainNode:
    image: kadlab:latest
    build:
      dockerfile: Dockerfile 
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      kademlia_network:
        ipv4_address: 10.0.1.2

  kademliaNodes:
    image: kadlab:latest # Make sure your Docker image has this name.
    build:
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 49  
#        resources:
#           limits:
#              cpus: "0.1"
#              memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    ports:
#      - "4000-4003:8081"
      - "4000-4048:8081"
    networks:
      - kademlia_network
    depends_on:
      - kademliaMainNode


networks:
  kademlia_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24


